### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by cdavid14** [leandrotsampa/hisilicon#2]
Opa boa noite @leandrotsampa , poderia fornecer a documentação que você utilizou pra fazer essa lib? Já posso ajudar também com futuras implementações.

Abraços

**Comment by leandrotsampa** [comment]
> 
> 
> Opa boa noite @leandrotsampa , poderia fornecer a documentação que você utilizou pra fazer essa lib? Já posso ajudar também com futuras implementações.
> 
> Abraços

Olá @cdavid14 fico feliz que tenha se interessado.
Eu utilizei como base o SDK **HiSTBLinuxV100R005C00SPC030**, onde converti pelo menos a parte de IR (Controle Remoto) e SCI (Leitor de Cartão) para GoLang com sucesso.

**Comment by cdavid14** [comment]
opa não tenho acesso a esse SDK infelizmente, poderia me mandar por email? listas@cdavid.eti.br

**Comment by leandrotsampa** [comment]
Enviado.
